<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class pokemon {


	private  $nom;
	private  $vie;
	private  $niveau;
	private  $attaque1;
    private  $attaque2;
    private  $description_attaque1;
    private  $description_attaque2;
	private  $photo;
	private  $faiblesse;
	private  $resistance;
	private  $description;
	private  $coup_sort_1;
	private  $coup_sort_2;
	private  $type_sort_1;
	private  $type_sort_2;
	private  $numero_pokedex;
	private  $espece;
	private  $taille;
    private  $poids;
    public function __construct() {
        
    }
	public function attaque() {

	}
	public function retraite() {
        
    }
    //set


}
?>